import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../../../core/theme/app_theme.dart';

/// Lease Generator Screen - AI-powered lease agreement creation
class LeaseGeneratorScreen extends ConsumerStatefulWidget {
  const LeaseGeneratorScreen({super.key});

  @override
  ConsumerState<LeaseGeneratorScreen> createState() => _LeaseGeneratorScreenState();
}

class _LeaseGeneratorScreenState extends ConsumerState<LeaseGeneratorScreen> {
  final _formKey = GlobalKey<FormState>();
  
  // Form controllers
  final _tenantNameController = TextEditingController();
  final _tenantEmailController = TextEditingController();
  final _propertyAddressController = TextEditingController();
  final _monthlyRentController = TextEditingController();
  final _securityDepositController = TextEditingController();
  final _leaseDurationController = TextEditingController(text: '12');
  
  String _selectedPropertyType = 'Apartment';
  String _selectedLeaseType = 'Fixed Term';
  DateTime _startDate = DateTime.now();
  bool _isGenerating = false;
  String? _generatedLease;

  final List<String> _propertyTypes = ['Apartment', 'House', 'Condo', 'Townhouse'];
  final List<String> _leaseTypes = ['Fixed Term', 'Month-to-Month', 'Lease-to-Own'];

  @override
  void dispose() {
    _tenantNameController.dispose();
    _tenantEmailController.dispose();
    _propertyAddressController.dispose();
    _monthlyRentController.dispose();
    _securityDepositController.dispose();
    _leaseDurationController.dispose();
    super.dispose();
  }

  Future<void> _generateLease() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isGenerating = true);

    // Simulate AI generation (replace with actual API call)
    await Future.delayed(const Duration(seconds: 2));

    setState(() {
      _generatedLease = '''
RESIDENTIAL LEASE AGREEMENT

This Lease Agreement ("Agreement") is entered into on ${_startDate.toString().split(' ')[0]} between:

LANDLORD: [Your Name/Company]
TENANT: ${_tenantNameController.text}

PROPERTY ADDRESS: ${_propertyAddressController.text}

1. LEASE TERM
   This lease shall commence on ${_startDate.toString().split(' ')[0]} and continue for a period of ${_leaseDurationController.text} months.

2. RENT PAYMENT
   Monthly Rent: \$${_monthlyRentController.text}
   Security Deposit: \$${_securityDepositController.text}
   Payment Due: 1st of each month

3. PROPERTY TYPE: $_selectedPropertyType

4. TENANT RESPONSIBILITIES
   - Maintain property in good condition
   - Pay utilities as specified
   - Provide 30 days notice before vacating
   - No unauthorized modifications

5. LANDLORD RESPONSIBILITIES
   - Maintain structural integrity
   - Address maintenance requests within 48 hours
   - Provide habitable living conditions
   - Respect tenant's privacy rights

6. COMPLIANCE
   This agreement complies with local housing regulations and tenant protection laws.

7. TERMINATION
   Either party may terminate with 30 days written notice, subject to lease terms.

TENANT SIGNATURE: _________________________ DATE: _________
LANDLORD SIGNATURE: _______________________ DATE: _________

Generated by REX AI - Residex Lease Sentinel
''';
      _isGenerating = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [AppColors.primaryCyan.withOpacity(0.3), AppColors.primaryBlue.withOpacity(0.3)],
                ),
                borderRadius: BorderRadius.circular(12),
              ),
              child: const Icon(Icons.description_outlined, color: AppColors.primaryCyan, size: 24),
            ),
            const SizedBox(width: 12),
            const Text('Lease Generator', style: TextStyle(color: Colors.white, fontSize: 20)),
          ],
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: _generatedLease == null ? _buildForm() : _buildGeneratedLease(),
    );
  }

  Widget _buildForm() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Form(
        key: _formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [AppColors.primaryCyan.withOpacity(0.1), AppColors.primaryBlue.withOpacity(0.1)],
                ),
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: AppColors.primaryCyan.withOpacity(0.3)),
              ),
              child: Row(
                children: [
                  Icon(Icons.auto_awesome, color: AppColors.primaryCyan, size: 32),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'AI-Powered Lease Creation',
                          style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          'Generate compliant lease agreements in seconds',
                          style: TextStyle(color: AppColors.slate400, fontSize: 14),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 32),

            // Tenant Information Section
            _buildSectionHeader('Tenant Information', Icons.person_outline),
            const SizedBox(height: 16),
            _buildTextField(
              controller: _tenantNameController,
              label: 'Tenant Full Name',
              icon: Icons.person,
              validator: (val) => val?.isEmpty ?? true ? 'Required' : null,
            ),
            const SizedBox(height: 16),
            _buildTextField(
              controller: _tenantEmailController,
              label: 'Tenant Email',
              icon: Icons.email_outlined,
              keyboardType: TextInputType.emailAddress,
              validator: (val) => val?.isEmpty ?? true ? 'Required' : null,
            ),

            const SizedBox(height: 32),

            // Property Information Section
            _buildSectionHeader('Property Information', Icons.home_outlined),
            const SizedBox(height: 16),
            _buildTextField(
              controller: _propertyAddressController,
              label: 'Property Address',
              icon: Icons.location_on_outlined,
              maxLines: 2,
              validator: (val) => val?.isEmpty ?? true ? 'Required' : null,
            ),
            const SizedBox(height: 16),
            _buildDropdown(
              value: _selectedPropertyType,
              label: 'Property Type',
              icon: Icons.apartment,
              items: _propertyTypes,
              onChanged: (val) => setState(() => _selectedPropertyType = val!),
            ),

            const SizedBox(height: 32),

            // Lease Terms Section
            _buildSectionHeader('Lease Terms', Icons.article_outlined),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: _buildTextField(
                    controller: _monthlyRentController,
                    label: 'Monthly Rent (\$)',
                    icon: Icons.attach_money,
                    keyboardType: TextInputType.number,
                    validator: (val) => val?.isEmpty ?? true ? 'Required' : null,
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: _buildTextField(
                    controller: _securityDepositController,
                    label: 'Security Deposit (\$)',
                    icon: Icons.security,
                    keyboardType: TextInputType.number,
                    validator: (val) => val?.isEmpty ?? true ? 'Required' : null,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: _buildTextField(
                    controller: _leaseDurationController,
                    label: 'Duration (months)',
                    icon: Icons.calendar_today,
                    keyboardType: TextInputType.number,
                    validator: (val) => val?.isEmpty ?? true ? 'Required' : null,
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: _buildDropdown(
                    value: _selectedLeaseType,
                    label: 'Lease Type',
                    icon: Icons.document_scanner,
                    items: _leaseTypes,
                    onChanged: (val) => setState(() => _selectedLeaseType = val!),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            _buildDatePicker(),

            const SizedBox(height: 40),

            // Generate Button
            SizedBox(
              width: double.infinity,
              height: 56,
              child: ElevatedButton(
                onPressed: _isGenerating ? null : _generateLease,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primaryCyan,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  elevation: 0,
                ),
                child: _isGenerating
                    ? const SizedBox(
                        height: 24,
                        width: 24,
                        child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
                      )
                    : Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: const [
                          Icon(Icons.auto_awesome, size: 24),
                          SizedBox(width: 12),
                          Text('Generate Lease Agreement', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                        ],
                      ),
              ),
            ),

            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  Widget _buildGeneratedLease() {
    return Column(
      children: [
        Expanded(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: AppColors.surface,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: AppColors.primaryCyan.withOpacity(0.3)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Icon(Icons.check_circle, color: AppColors.primaryCyan, size: 32),
                      const SizedBox(width: 12),
                      const Expanded(
                        child: Text(
                          'Lease Agreement Generated',
                          style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 24),
                  Text(
                    _generatedLease!,
                    style: TextStyle(color: AppColors.slate300, fontSize: 14, height: 1.6),
                  ),
                ],
              ),
            ),
          ),
        ),
        Container(
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: AppColors.surface,
            border: Border(top: BorderSide(color: AppColors.slate700)),
          ),
          child: Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: () => setState(() => _generatedLease = null),
                  icon: const Icon(Icons.edit),
                  label: const Text('Edit Details'),
                  style: OutlinedButton.styleFrom(
                    foregroundColor: AppColors.primaryCyan,
                    side: BorderSide(color: AppColors.primaryCyan),
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: ElevatedButton.icon(
                  onPressed: () {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('Lease downloaded successfully!')),
                    );
                  },
                  icon: const Icon(Icons.download),
                  label: const Text('Download PDF'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primaryCyan,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildSectionHeader(String title, IconData icon) {
    return Row(
      children: [
        Icon(icon, color: AppColors.primaryCyan, size: 24),
        const SizedBox(width: 12),
        Text(
          title,
          style: const TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
        ),
      ],
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required IconData icon,
    TextInputType? keyboardType,
    int maxLines = 1,
    String? Function(String?)? validator,
  }) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      maxLines: maxLines,
      validator: validator,
      style: const TextStyle(color: Colors.white),
      decoration: InputDecoration(
        labelText: label,
        labelStyle: TextStyle(color: AppColors.slate400),
        prefixIcon: Icon(icon, color: AppColors.primaryCyan),
        filled: true,
        fillColor: AppColors.surface,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.slate700),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.slate700),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.primaryCyan),
        ),
      ),
    );
  }

  Widget _buildDropdown({
    required String value,
    required String label,
    required IconData icon,
    required List<String> items,
    required Function(String?) onChanged,
  }) {
    return DropdownButtonFormField<String>(
      value: value,
      onChanged: onChanged,
      style: const TextStyle(color: Colors.white),
      dropdownColor: AppColors.surface,
      decoration: InputDecoration(
        labelText: label,
        labelStyle: TextStyle(color: AppColors.slate400),
        prefixIcon: Icon(icon, color: AppColors.primaryCyan),
        filled: true,
        fillColor: AppColors.surface,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.slate700),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.slate700),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.primaryCyan),
        ),
      ),
      items: items.map((item) {
        return DropdownMenuItem(
          value: item,
          child: Text(item),
        );
      }).toList(),
    );
  }

  Widget _buildDatePicker() {
    return InkWell(
      onTap: () async {
        final date = await showDatePicker(
          context: context,
          initialDate: _startDate,
          firstDate: DateTime.now(),
          lastDate: DateTime.now().add(const Duration(days: 365)),
          builder: (context, child) {
            return Theme(
              data: ThemeData.dark().copyWith(
                colorScheme: ColorScheme.dark(
                  primary: AppColors.primaryCyan,
                  surface: AppColors.surface,
                ),
              ),
              child: child!,
            );
          },
        );
        if (date != null) {
          setState(() => _startDate = date);
        }
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        decoration: BoxDecoration(
          color: AppColors.surface,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: AppColors.slate700),
        ),
        child: Row(
          children: [
            Icon(Icons.calendar_today, color: AppColors.primaryCyan),
            const SizedBox(width: 16),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Start Date',
                  style: TextStyle(color: AppColors.slate400, fontSize: 12),
                ),
                const SizedBox(height: 4),
                Text(
                  '${_startDate.day}/${_startDate.month}/${_startDate.year}',
                  style: const TextStyle(color: Colors.white, fontSize: 16),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
