import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../../core/theme/app_theme.dart';
import '../../../domain/entities/property.dart';
import '../../providers/property_providers.dart';
import '../../../../shared/presentation/providers/auth_providers.dart';

/// Add/Edit property dialog.
///
/// Dual-mode: when [property] is null this dialog creates a new property.
/// When [property] is non-null, all fields are pre-filled from it and
/// submitting saves changes via the update path instead of create.
class AddPropertyDialog extends ConsumerStatefulWidget {
  final Property? property;

  const AddPropertyDialog({super.key, this.property});

  @override
  ConsumerState<AddPropertyDialog> createState() => _AddPropertyDialogState();
}

class _AddPropertyDialogState extends ConsumerState<AddPropertyDialog> {
  final _formKey = GlobalKey<FormState>();
  
  // Form controllers
  final _nameController = TextEditingController();
  final _streetController = TextEditingController();
  final _cityController = TextEditingController();
  final _stateController = TextEditingController();
  final _zipCodeController = TextEditingController();
  final _purchasePriceController = TextEditingController();
  final _currentValueController = TextEditingController();
  final _totalUnitsController = TextEditingController();
  final _occupiedUnitsController = TextEditingController();
  final _monthlyRentController = TextEditingController();
  
  PropertyType _selectedType = PropertyType.apartment;
  bool _isLoading = false;

  bool get _isEditMode => widget.property != null;

  @override
  void initState() {
    super.initState();
    final property = widget.property;
    if (property != null) {
      _nameController.text = property.name;
      _streetController.text = property.address.street;
      _cityController.text = property.address.city;
      _stateController.text = property.address.state;
      _zipCodeController.text = property.address.zipCode;
      _purchasePriceController.text = property.purchasePrice.toString();
      _currentValueController.text = property.currentValue.toString();
      _totalUnitsController.text = property.totalUnits.toString();
      _occupiedUnitsController.text = property.occupiedUnits.toString();
      _monthlyRentController.text = property.monthlyRent.toString();
      _selectedType = property.type;
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _streetController.dispose();
    _cityController.dispose();
    _stateController.dispose();
    _zipCodeController.dispose();
    _purchasePriceController.dispose();
    _currentValueController.dispose();
    _totalUnitsController.dispose();
    _occupiedUnitsController.dispose();
    _monthlyRentController.dispose();
    super.dispose();
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;

    final user = ref.read(currentFirebaseUserProvider);
    if (user == null) {
      _showError('User not authenticated');
      return;
    }

    setState(() => _isLoading = true);

    try {
      final address = PropertyAddress(
        street: _streetController.text.trim(),
        city: _cityController.text.trim(),
        state: _stateController.text.trim(),
        zipCode: _zipCodeController.text.trim(),
        country: 'USA', // Default to USA
      );

      final controller = ref.read(propertyControllerProvider);
      final existing = widget.property;

      if (existing != null) {
        // Edit mode: preserve id/landlordId/createdAt/photos, update the rest.
        final updatedProperty = existing.copyWith(
          name: _nameController.text.trim(),
          address: address,
          type: _selectedType,
          purchasePrice: double.parse(_purchasePriceController.text),
          currentValue: double.parse(_currentValueController.text),
          totalUnits: int.parse(_totalUnitsController.text),
          occupiedUnits: int.parse(_occupiedUnitsController.text),
          monthlyRent: double.parse(_monthlyRentController.text),
        );
        await controller.updateProperty(updatedProperty);
      } else {
        final property = Property(
          id: '', // Will be generated by Firestore
          landlordId: user.uid,
          name: _nameController.text.trim(),
          address: address,
          type: _selectedType,
          purchasePrice: double.parse(_purchasePriceController.text),
          currentValue: double.parse(_currentValueController.text),
          totalUnits: int.parse(_totalUnitsController.text),
          occupiedUnits: int.parse(_occupiedUnitsController.text),
          monthlyRent: double.parse(_monthlyRentController.text),
          photos: [],
          createdAt: DateTime.now(),
        );
        await controller.createProperty(property);
      }

      if (mounted) {
        Navigator.of(context).pop(true); // Return success
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(_isEditMode
                ? '✅ Property updated successfully!'
                : '✅ Property added successfully!'),
            backgroundColor: AppColors.success,
            duration: const Duration(seconds: 2),
          ),
        );
      }
    } catch (e) {
      _showError(_isEditMode
          ? 'Failed to update property: $e'
          : 'Failed to add property: $e');
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  void _showError(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: AppColors.error,
        duration: const Duration(seconds: 3),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: AppColors.paper,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(20),
      ),
      child: Container(
        constraints: const BoxConstraints(maxWidth: 600, maxHeight: 700),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Header
            Container(
              padding: const EdgeInsets.all(20),
              decoration: const BoxDecoration(
                color: AppColors.registry,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20),
                  topRight: Radius.circular(20),
                ),
              ),
              child: Row(
                children: [
                  Icon(
                    _isEditMode ? Icons.edit_outlined : Icons.business,
                    color: Colors.white,
                    size: 28,
                  ),
                  const SizedBox(width: 12),
                  Text(
                    _isEditMode ? 'Edit property' : 'Add New Property',
                    style: AppTextStyles.headlineMedium.copyWith(
                      color: Colors.white,
                    ),
                  ),
                  const Spacer(),
                  IconButton(
                    onPressed: () => Navigator.of(context).pop(),
                    icon: const Icon(Icons.close, color: Colors.white),
                  ),
                ],
              ),
            ),

            // Form
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(24),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      _buildTextField(
                        controller: _nameController,
                        label: 'Property Name',
                        hint: 'e.g., Sunset Apartments',
                        icon: Icons.apartment,
                        validator: (value) =>
                            value?.isEmpty ?? true ? 'Required' : null,
                      ),
                      const SizedBox(height: 16),

                      // Property Type Dropdown
                      _buildDropdown(),
                      const SizedBox(height: 20),

                      Text(
                        'Address',
                        style: AppTextStyles.labelLarge.copyWith(
                          color: AppColors.textMuted,
                        ),
                      ),
                      const SizedBox(height: 12),
                      _buildTextField(
                        controller: _streetController,
                        label: 'Street Address',
                        hint: '123 Main St',
                        icon: Icons.location_on,
                        validator: (value) =>
                            value?.isEmpty ?? true ? 'Required' : null,
                      ),
                      const SizedBox(height: 12),
                      _buildTextField(
                        controller: _cityController,
                        label: 'City',
                        hint: 'New York',
                        validator: (value) =>
                            value?.isEmpty ?? true ? 'Required' : null,
                      ),
                      const SizedBox(height: 12),
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              controller: _stateController,
                              label: 'State',
                              hint: 'NY',
                              validator: (value) =>
                                  value?.isEmpty ?? true ? 'Required' : null,
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: _buildTextField(
                              controller: _zipCodeController,
                              label: 'Zip Code',
                              hint: '10001',
                              keyboardType: TextInputType.number,
                              validator: (value) =>
                                  value?.isEmpty ?? true ? 'Required' : null,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 20),

                      Text(
                        'Financial Details',
                        style: AppTextStyles.labelLarge.copyWith(
                          color: AppColors.textMuted,
                        ),
                      ),
                      const SizedBox(height: 12),
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              controller: _purchasePriceController,
                              label: 'Purchase Price',
                              hint: '500000',
                              keyboardType: TextInputType.number,
                              validator: _validateNumber,
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: _buildTextField(
                              controller: _currentValueController,
                              label: 'Current Value',
                              hint: '550000',
                              keyboardType: TextInputType.number,
                              validator: _validateNumber,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 12),
                      _buildTextField(
                        controller: _monthlyRentController,
                        label: 'Monthly Rent (per unit)',
                        hint: '2000',
                        icon: Icons.payment,
                        keyboardType: TextInputType.number,
                        validator: _validateNumber,
                      ),
                      const SizedBox(height: 20),

                      Text(
                        'Unit Information',
                        style: AppTextStyles.labelLarge.copyWith(
                          color: AppColors.textMuted,
                        ),
                      ),
                      const SizedBox(height: 12),
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              controller: _totalUnitsController,
                              label: 'Total Units',
                              hint: '10',
                              keyboardType: TextInputType.number,
                              validator: _validatePositiveInt,
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: _buildTextField(
                              controller: _occupiedUnitsController,
                              label: 'Occupied Units',
                              hint: '8',
                              keyboardType: TextInputType.number,
                              validator: (value) {
                                final error = _validatePositiveInt(value);
                                if (error != null) return error;
                                
                                final occupied = int.tryParse(value!) ?? 0;
                                final total = int.tryParse(_totalUnitsController.text) ?? 0;
                                
                                if (occupied > total) {
                                  return 'Cannot exceed total units';
                                }
                                return null;
                              },
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ),

            // Footer buttons
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: AppColors.surfaceLight,
                border: Border(
                  top: BorderSide(color: AppColors.hairline),
                ),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: _isLoading ? null : () => Navigator.of(context).pop(),
                    child: Text(
                      'Cancel',
                      style: TextStyle(color: AppColors.textMuted),
                    ),
                  ),
                  const SizedBox(width: 12),
                  ElevatedButton(
                    onPressed: _isLoading ? null : _handleSubmit,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.registry,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(
                        horizontal: 32,
                        vertical: 12,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: _isLoading
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              valueColor: AlwaysStoppedAnimation(Colors.white),
                            ),
                          )
                        : Text(_isEditMode ? 'Save changes' : 'Add Property'),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    String? hint,
    IconData? icon,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
  }) {
    return TextFormField(
      controller: controller,
      keyboardType: keyboardType,
      style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textPrimary),
      decoration: InputDecoration(
        labelText: label,
        labelStyle: AppTextStyles.bodySmall.copyWith(color: AppColors.textMuted),
        floatingLabelStyle: AppTextStyles.bodySmall.copyWith(color: AppColors.registry),
        floatingLabelBehavior: FloatingLabelBehavior.always,
        isDense: true,
        hintText: hint,
        prefixIcon: icon != null ? Icon(icon, color: AppColors.registry, size: 20) : null,
        filled: true,
        fillColor: AppColors.card,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.hairline),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.hairline),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.registry, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.error),
        ),
      ),
      validator: validator,
    );
  }

  Widget _buildDropdown() {
    return DropdownButtonFormField<PropertyType>(
      value: _selectedType,
      onChanged: (value) {
        if (value != null) {
          setState(() => _selectedType = value);
        }
      },
      decoration: InputDecoration(
        labelText: 'Property Type',
        labelStyle: AppTextStyles.bodySmall.copyWith(color: AppColors.textMuted),
        floatingLabelBehavior: FloatingLabelBehavior.auto,
        isDense: true,
        prefixIcon: const Icon(Icons.category, color: AppColors.registry),
        filled: true,
        fillColor: AppColors.card,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.hairline),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.hairline),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: AppColors.registry, width: 2),
        ),
      ),
      dropdownColor: AppColors.card,
      style: AppTextStyles.bodyMedium.copyWith(color: AppColors.textPrimary),
      items: PropertyType.values.map((type) {
        return DropdownMenuItem(
          value: type,
          child: Text(type.displayName),
        );
      }).toList(),
    );
  }

  String? _validateNumber(String? value) {
    if (value == null || value.isEmpty) return 'Required';
    if (double.tryParse(value) == null) return 'Must be a number';
    if (double.parse(value) < 0) return 'Must be positive';
    return null;
  }

  String? _validatePositiveInt(String? value) {
    if (value == null || value.isEmpty) return 'Required';
    final number = int.tryParse(value);
    if (number == null) return 'Must be a whole number';
    if (number <= 0) return 'Must be greater than 0';
    return null;
  }
}
